apiVersion : v1
kind: ConfigMap
metadata:
  name: mercedes-benz-swapi-consumer
  namespace: mercedes-benz
  labels:
    app: mercedes-benz-swapi-consumer
data:
  debug: "false" # Set to true if debugging logs are desired. Also, set to true to see Spring's "Condition Evaluation Report"
  spring.application.name: "mercedes-benz-swapi-consumer"
  spring.jackson.serialization.wrap-root-value: "false"

  springdoc.api-docs.enabled: "true"
  springdoc.api-docs.path: "/swapi-consumer/doc/api-docs"

  springdoc.swagger-ui.enabled: "true"
  springdoc.swagger-ui.path: "/swapi-consumer/doc/swagger-ui-custom.html"
  springdoc.swagger-ui.operationsSorter: "method"
  springdoc.swagger-ui.swagger-server-url: "http://traefik.valen.net/" # NOTICE! PORT 8080

  management.metrics.enable.jvm: "true"
  management.metrics.enable.logback: "true"

  management.endpoints.enabled-by-default: "true"
  management.endpoints.web.exposure.include: "*"

  management.endpoint.info.enabled: "true"

  management.health.show.details: "always"
  management.health.defaults.enabled: "true"
  management.health.diskspace.enabled: "true"
  management.health.livenessstate.enabled: "true"
  management.health.readinessstate.enabled: "true"

  #LOGBACK_PATTERN: "%d{ISO8601} |  %highlight(%-5.5level) | %-20.20thread | %-32.40X{requestId:-No requestId} | %-50.50logger{36} | %green(%msg%n)"
  logging.file.name: "/logs/swapi-consumer.log"

  logging.pattern.dateformat: "yyyy-MM-dd HH:mm:ss.SSS,Europe/Madrid"

  logging.level.root: "INFO"
  logging.level.org.springframework.web: "INFO"
  logging.level.org.springframework.web.servlet.DispatcherServlet: "INFO"
  logging.level.org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor: "INFO"
  logging.level.org.springframework.security: "INFO"

  logging.logback.rollingpolicy.clean-history-on-start: "true"

  server.port: "8080"

  app.swapi.serverURL: "https://swapi.dev/api"
  app.swapi.peopleEndpointPath: "/people"
  app.swapi.timeout.connectionMillis: "60000"
  app.swapi.timeout.readMillis: "60000"

  app.swaggerprefix: "/swapi-consumer/doc"

  app.resttemplate.timeout.millisConnectionTimeout: "60000"
  app.resttemplate.timeout.millisReadTimeout: "60000"
