apiVersion: v1
kind: Service
metadata:
  name: mercedes-benz-swapi-consumer
  namespace: mercedes-benz
  labels:
    app: mercedes-benz-swapi-consumer
spec:
  type: ClusterIP # TODO: change to ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mercedes-benz-swapi-consumer
